-- =============================================================================
-- Real-Time Chat Application
-- PostgreSQL DDL
-- =============================================================================
-- Conventions:
--   - All primary keys are UUIDs generated by gen_random_uuid()
--   - All timestamps are stored in UTC as TIMESTAMP WITH TIME ZONE
--   - Foreign keys have explicit ON DELETE behavior defined
--   - Indexes are created on all foreign keys and frequently queried columns
-- =============================================================================


-- -----------------------------------------------------------------------------
-- Extensions
-- -----------------------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS "pgcrypto";  -- provides gen_random_uuid()


-- -----------------------------------------------------------------------------
-- USERS
-- Central entity. Owns rooms, sends messages, has sessions and contacts.
-- -----------------------------------------------------------------------------

CREATE TABLE users (
    id              UUID                        PRIMARY KEY DEFAULT gen_random_uuid(),
    username        VARCHAR(50)                 NOT NULL,
    email           VARCHAR(255)                NOT NULL,
    password_hash   VARCHAR(255)                NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT NOW(),
    last_seen_at    TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_users_username    UNIQUE (username),
    CONSTRAINT uq_users_email       UNIQUE (email),
    CONSTRAINT ck_users_username_length
        CHECK (char_length(username) >= 3),
    CONSTRAINT ck_users_email_format
        CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
);

COMMENT ON TABLE  users                 IS 'Registered user accounts.';
COMMENT ON COLUMN users.password_hash   IS 'bcrypt hash of the user password. Never store plaintext.';
COMMENT ON COLUMN users.last_seen_at    IS 'Updated on socket connect/disconnect. Used for presence display.';


-- -----------------------------------------------------------------------------
-- ROOMS
-- A chat room owned by a user. Supports public and private rooms.
-- -----------------------------------------------------------------------------

CREATE TABLE rooms (
    id              UUID                        PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id        UUID                        NOT NULL,
    name            VARCHAR(50)                 NOT NULL,
    description     VARCHAR(255),
    is_private      BOOLEAN                     NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_rooms_owner
        FOREIGN KEY (owner_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT uq_rooms_name    UNIQUE (name),
    CONSTRAINT ck_rooms_name_length
        CHECK (char_length(name) >= 1)
);

COMMENT ON TABLE  rooms             IS 'Chat rooms created by users.';
COMMENT ON COLUMN rooms.owner_id    IS 'The user who created the room. Cascade deletes the room if the owner is deleted.';
COMMENT ON COLUMN rooms.is_private  IS 'Private rooms are not shown in the public room list.';

CREATE INDEX idx_rooms_owner_id ON rooms (owner_id);


-- -----------------------------------------------------------------------------
-- ROOM_MEMBERS
-- Junction table linking users to rooms. Tracks membership and unread counts.
-- -----------------------------------------------------------------------------

CREATE TABLE room_members (
    id              UUID                        PRIMARY KEY DEFAULT gen_random_uuid(),
    room_id         UUID                        NOT NULL,
    user_id         UUID                        NOT NULL,
    joined_at       TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT NOW(),
    unread_count    INTEGER                     NOT NULL DEFAULT 0,

    CONSTRAINT fk_room_members_room
        FOREIGN KEY (room_id)
        REFERENCES rooms (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_room_members_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT uq_room_members_room_user
        UNIQUE (room_id, user_id),

    CONSTRAINT ck_room_members_unread_count
        CHECK (unread_count >= 0)
);

COMMENT ON TABLE  room_members                  IS 'Membership records linking users to rooms.';
COMMENT ON COLUMN room_members.unread_count     IS 'Per-user unread message count for this room. Reset to 0 when the user views the room.';
COMMENT ON COLUMN room_members.joined_at        IS 'Timestamp of when the user joined the room.';

CREATE INDEX idx_room_members_room_id   ON room_members (room_id);
CREATE INDEX idx_room_members_user_id   ON room_members (user_id);


-- -----------------------------------------------------------------------------
-- MESSAGES
-- All messages sent in a room, including system-generated event messages.
-- -----------------------------------------------------------------------------

CREATE TABLE messages (
    id                  UUID                        PRIMARY KEY DEFAULT gen_random_uuid(),
    room_id             UUID                        NOT NULL,
    sender_id           UUID                        NOT NULL,
    body                TEXT                        NOT NULL,
    is_system_message   BOOLEAN                     NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_messages_room
        FOREIGN KEY (room_id)
        REFERENCES rooms (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_messages_sender
        FOREIGN KEY (sender_id)
        REFERENCES users (id)
        ON DELETE SET NULL,

    CONSTRAINT ck_messages_body_length
        CHECK (char_length(body) >= 1 AND char_length(body) <= 1000)
);

COMMENT ON TABLE  messages                      IS 'Messages sent within a room.';
COMMENT ON COLUMN messages.sender_id            IS 'Set to NULL if the sending user is deleted. Message body is preserved.';
COMMENT ON COLUMN messages.is_system_message    IS 'TRUE for system events such as join/leave notices. Rendered differently in the UI.';
COMMENT ON COLUMN messages.body                 IS 'Message content. Max 1000 characters as defined in US-301.';

CREATE INDEX idx_messages_room_id       ON messages (room_id);
CREATE INDEX idx_messages_sender_id     ON messages (sender_id);
CREATE INDEX idx_messages_created_at    ON messages (created_at DESC);


-- -----------------------------------------------------------------------------
-- SESSIONS
-- Tracks active and historical Socket.io connections for presence management.
-- -----------------------------------------------------------------------------

CREATE TABLE sessions (
    id                  UUID                        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             UUID                        NOT NULL,
    socket_id           VARCHAR(255)                NOT NULL,
    is_online           BOOLEAN                     NOT NULL DEFAULT TRUE,
    connected_at        TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT NOW(),
    disconnected_at     TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_sessions_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT uq_sessions_socket_id
        UNIQUE (socket_id),

    CONSTRAINT ck_sessions_disconnect_after_connect
        CHECK (disconnected_at IS NULL OR disconnected_at >= connected_at)
);

COMMENT ON TABLE  sessions                      IS 'Socket.io connection records. Used to manage online presence (US-401).';
COMMENT ON COLUMN sessions.socket_id            IS 'The Socket.io socket ID assigned at connection time.';
COMMENT ON COLUMN sessions.is_online            IS 'TRUE while the socket is connected. Set to FALSE on disconnect event.';
COMMENT ON COLUMN sessions.disconnected_at      IS 'NULL while session is active. Set when the socket disconnects.';

CREATE INDEX idx_sessions_user_id   ON sessions (user_id);
CREATE INDEX idx_sessions_is_online ON sessions (is_online);


-- -----------------------------------------------------------------------------
-- CONTACTS
-- Optional contacts attached to a user. Supports recruiter/contact tracking
-- if the app is extended. Included per the original feature outline.
-- -----------------------------------------------------------------------------

CREATE TABLE contacts (
    id              UUID                        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID                        NOT NULL,
    name            VARCHAR(100)                NOT NULL,
    email           VARCHAR(255),
    phone           VARCHAR(30),
    linkedin_url    VARCHAR(500),
    created_at      TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_contacts_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT ck_contacts_email_format
        CHECK (
            email IS NULL OR
            email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
        ),

    CONSTRAINT ck_contacts_linkedin_url_format
        CHECK (
            linkedin_url IS NULL OR
            linkedin_url ~* '^https?://(www\.)?linkedin\.com/.*$'
        )
);

COMMENT ON TABLE  contacts              IS 'User-owned contact records. Optional feature from the original outline.';
COMMENT ON COLUMN contacts.user_id      IS 'The user who owns this contact. Cascade deletes contacts if the user is deleted.';
COMMENT ON COLUMN contacts.email        IS 'Optional. Validated by regex check constraint.';
COMMENT ON COLUMN contacts.linkedin_url IS 'Optional. Must be a valid LinkedIn URL if provided.';

CREATE INDEX idx_contacts_user_id ON contacts (user_id);


-- =============================================================================
-- Helper Views
-- =============================================================================

-- Active sessions view: returns the most recent session per user
CREATE VIEW active_sessions AS
    SELECT DISTINCT ON (user_id)
        user_id,
        socket_id,
        is_online,
        connected_at
    FROM sessions
    ORDER BY user_id, connected_at DESC;

COMMENT ON VIEW active_sessions IS 'Returns the most recent session record per user. Use to determine current online status.';


-- Room summary view: returns rooms with member count and latest message timestamp
CREATE VIEW room_summary AS
    SELECT
        r.id,
        r.name,
        r.description,
        r.is_private,
        r.owner_id,
        r.created_at,
        COUNT(DISTINCT rm.user_id)      AS member_count,
        MAX(m.created_at)               AS last_message_at
    FROM rooms r
    LEFT JOIN room_members  rm  ON rm.room_id = r.id
    LEFT JOIN messages      m   ON m.room_id  = r.id
    GROUP BY r.id;

COMMENT ON VIEW room_summary IS 'Aggregated room data including member count and latest message timestamp. Use for the room list sidebar.';


-- =============================================================================
-- End of DDL
-- =============================================================================